backend:
  name: git-gateway

media_folder: static/images/uploads
public_folder: images/uploads
publish_mode: editorial_workflow

collections:
  - label: 'Landing Page'
    name: 'Landing Page'
    files:
      - label: Home Page
        name: home
        file: content/home.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro text, name: intro, widget: text }
          - { label: Image, name: image, widget: image }
  - name: weiss
    label: Weiss
    create: true
    folder: content/weiss
    slug: '{{name}}'
    fields:
      - { label: Name, name: name, widget: string }
      - { label: ASIN, name: asin", widget: string }
      - { label: Product Type, name: producttype, widget: string }
      - { label: Series, name: series, widget: string }
      - { label: Description, name: description, widget: text, required: false }
      - { label: Image, name: image, widget: image }
      - {
          label: Tags,
          name: tags,
          widget: select,
          multiple: true,
          min: 1,
          max: 3,
          options: ['Design', 'UX', 'Dev'],
          default: ['Design'],
        }
      - label: Pricings
        name: pricings
        widget: list
        summary: 'Quantity:{{fields.quantity}} - ${{fields.price}}'
        fields:
          - label: Quantity
            name: quantity
            widget: number
            min: 1
            valueType: int
          - label: Price
            name: price
            min: 0
            widget: number
            valueType: float
      - label: 'Testimonials'
        name: 'testimonials'
        widget: 'list'
        summary: '{{fields.quote}} - {{fields.author.name}}'
        fields:
          - {
              label: Quote,
              name: quote,
              widget: string,
              default: 'Everything is awesome!',
            }
          - label: Author
            name: author
            widget: object
            fields:
              - { label: Name, name: name, widget: string, default: 'Emmet' }
              - {
                  label: Avatar,
                  name: avatar,
                  widget: image,
                  default: '/img/emmet.jpg',
                }
