backend: 
    name: git-gateway

media_folder: static/images/uploads
public_folder: images/uploads
publish_mode: editorial_workflow

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro text, name: intro, widget: text}
          - {label: Image, name: image, widget: image}
  - name: "products"
    label: "Products"
    create: true
    folder: "content/products"
    slug: "{{name}}"
    fields:
      - {label: Name, name: name, widget: string}
      - {label: Product Type, name: producttype, widget: string}
      - {label: Series, name: series, widget: string}
      - {label: Description, name: description, widget: text, required: false}
      - {label: Max Quantity, name: maxquantity, valuetype: int, widget: number, default: 10}
      - {label: Image, name: image, widget: image}
  - name: "stuff"
    label: "stuff"
    create: true
    folder: "content/stuff"
    slug: "{{name}}"
    fields:
      - {label: Name, name: name, widget: string}
      - {label: Product Type, name: producttype, widget: string}
      - {label: Series, name: series, widget: string}
      - {label: Description, name: description, widget: text, required: false}
      - {label: Max Quantity, name: maxquantity, valuetype: int, widget: number, default: 10}
      - {label: Image, name: image, widget: image}