backend:
  name: git-gateway

# when using the default proxy server port
local_backend: true

media_folder: static/images
public_folder: /images
publish_mode: editorial_workflow

collections:
  - label: 'Landing Page'
    name: 'landingPage'
    files:
      - label: Landing Page
        name: landing
        file: content/landingPage.md
        media_folder: 'images'
        public_folder: '/images'
        fields:
          - { label: Landing Text, name: landingText, widget: string }
          - { label: Landing Subtitle, name: landingSubtitle, widget: string }
          - { label: Landing Image, name: landingImage, widget: image }
          - {
              label: New Release 1,
              name: release1,
              widget: relation,
              collection: weiss,
              searchFields: ['series', 'producttype', 'name', 'asin'],
              valueField: 'asin',
              displayFields: ['series', 'producttype', 'name', 'asin'],
            }
          - {
              label: New Release 2,
              name: release2,
              widget: relation,
              collection: weiss,
              searchFields: ['series', 'producttype', 'name', 'asin'],
              valueField: 'asin',
              displayFields: ['series', 'producttype', 'name', 'asin'],
            }
          - {
              label: New Release 3,
              name: release3,
              widget: relation,
              collection: weiss,
              searchFields: ['series', 'producttype', 'name', 'asin'],
              valueField: 'asin',
              displayFields: ['series', 'producttype', 'name', 'asin'],
            }
  - name: weiss
    label: Weiss
    create: true
    folder: content/weiss
    media_folder: 'images'
    public_folder: ''
    slug: '{{name}}'
    fields:
      - { label: Name, name: name, widget: string }
      - { label: ASIN, name: asin, widget: string }
      - {
          label: Product Type,
          name: producttype,
          widget: select,
          options:
            [
              'Trial Deck',
              'Trial Deck+',
              'Box of Trial Decks',
              'Booster Box',
              'Carton of Booster Boxes',
              'Extra Booster',
              'Other',
            ],
          default: ['Booster Box'],
        }
      - { label: Series, name: series, widget: string }
      - { label: Product Primary Color Hex, name: color, widget: string }
      - { label: Description, name: description, widget: text, required: false }
      - { label: Image, name: image, widget: image }
      - label: Pricings
        name: pricings
        widget: list
        minimize_collapsed: true
        summary: '{{fields.quantity}} cost(s) ${{fields.price}}'
        fields:
          - label: Quantity
            name: quantity
            widget: number
            min: 1
            valueType: int
          - label: Price
            name: price
            min: 0
            widget: number
            valueType: float
      - {
          label: Shipping Weight,
          name: weight,
          widget: number,
          valueType: float,
          required: false,
          min: 0,
        }
      - {
          label: Preorder date,
          name: preorder,
          widget: datetime,
          required: false,
          dateFormat: 'MM.DD.YYYY',
          timeFormat: false,
        }
      - {
          label: Release date,
          name: release,
          widget: datetime,
          required: false,
          dateFormat: 'MM.DD.YYYY',
          timeFormat: false,
        }
