backend:
  name: git-gateway

# when using the default proxy server port
local_backend: true

media_folder: 'static/images'
public_folder: '/images/'
publish_mode: editorial_workflow

collections:
  - label: 'Page Info'
    name: 'pages'
    files:
      - label: 'Landing Page'
        name: landing
        file: content/landingPage.md
        media_folder: 'images'
        fields:
          - { label: Landing Text, name: landingText, widget: string }
          - { label: Landing Subtitle, name: landingSubtitle, widget: string }
          - { label: Landing Image, name: landingImage, widget: image }
          - {
              label: New Release 1,
              name: release1,
              widget: relation,
              collection: weiss,
              searchFields: ['series', 'producttype', 'name', 'asin'],
              valueField: 'asin',
              displayFields: ['series', 'producttype', 'name', 'asin'],
            }
          - {
              label: New Release 2,
              name: release2,
              widget: relation,
              collection: weiss,
              searchFields: ['series', 'producttype', 'name', 'asin'],
              valueField: 'asin',
              displayFields: ['series', 'producttype', 'name', 'asin'],
            }
          - {
              label: New Release 3,
              name: release3,
              widget: relation,
              collection: weiss,
              searchFields: ['series', 'producttype', 'name', 'asin'],
              valueField: 'asin',
              displayFields: ['series', 'producttype', 'name', 'asin'],
            }
  - name: productCategories
    label: 'Product Categories'
    create: true
    folder: content/productCategories
    media_folder: 'images'
    slug: '{{productCategory}}'
    fields:
      - { label: 'Product Category', name: productCategory, widget: string }
      - { label: Image, name: image, widget: image }
      - {
          label: Order of Product Category,
          name: order,
          default: 1,
          valueType: int,
          widget: number,
          min: 1,
        }
  - name: comiketEventInfo
    label: 'Comiket Event Information'
    create: true
    folder: content/comiketEvents
    media_folder: 'images'
    slug: '{{eventName}}'
    fields:
      - { label: Event Name, name: eventName, widget: string }
      - {
          label: 'Current Event?',
          name: currentEvent,
          widget: boolean,
          default: false,
        }
      - { label: Event Description, name: eventDesc, widget: string, required: false }
      - {
          label: Preorder date,
          name: preorder,
          widget: datetime,
          required: false,
          dateFormat: 'MM.DD.YYYY',
          timeFormat: false,
        }
      - {
          label: Estimated Receive date,
          name: receive,
          widget: datetime,
          required: false,
          dateFormat: 'MM.DD.YYYY',
          timeFormat: false,
        }

  - name: weiss
    label: Weiss
    create: true
    folder: content/weiss
    media_folder: 'images'
    identifier_field: asin
    slug: '{{slug}}'
    fields:
      - { label: Name, name: name, widget: string }
      - { label: ASIN, name: asin, widget: string }
      - {
          label: Product Type,
          name: producttype,
          widget: select,
          options:
            [
              'Trial Deck',
              'Trial Deck+',
              'Box of Trial Decks',
              'Booster Box',
              'Carton of Booster Boxes',
              'Extra Booster',
              'Other',
            ],
          default: ['Booster Box'],
        }
      - { label: Display Name, name: displayName, widget: string }
      - { label: Series, name: series, widget: string }
      - { label: Product Primary Color Hex, name: color, widget: string }
      - { label: Description, name: description, widget: text, required: false }
      - { label: Image, name: image, widget: image }
      - label: Pricings
        name: pricings
        widget: list
        minimize_collapsed: true
        summary: '{{fields.quantity}} cost(s) ${{fields.price}}'
        fields:
          - label: Quantity
            name: quantity
            widget: number
            min: 1
            valueType: int
          - label: Price
            name: price
            min: 0
            widget: number
            valueType: float
      - {
          label: Shipping Weight,
          name: weight,
          widget: number,
          valueType: float,
          required: false,
          min: 0,
        }
      - {
          label: Preorder date,
          name: preorder,
          widget: datetime,
          required: false,
          dateFormat: 'MM.DD.YYYY',
          timeFormat: false,
        }
      - {
          label: Release date,
          name: release,
          widget: datetime,
          required: false,
          dateFormat: 'MM.DD.YYYY',
          timeFormat: false,
        }
      - {
          label: 'Merchandise',
          name: 'merchandise',
          widget: 'hidden',
          default: 'weiss',
        }
  - name: comiket
    label: Comiket
    create: true
    folder: content/comiket
    media_folder: 'images'
    slug: '{{slug}}'
    identifier_field: 'asin'
    fields:
      - { label: Image, name: image, widget: image }
      - {
          label: Product Type,
          name: producttype,
          widget: select,
          options: ['Playmat', 'Sleeves'],
          default: ['Playmat'],
        }
      - {
          label: Event Name,
          name: eventName,
          widget: relation,
          collection: comiketEventInfo,
          searchFields: ['eventName'],
          valueField: 'eventName',
          displayFields: ['eventName'],
        }
      - {
          label: Shipping Weight,
          name: weight,
          widget: number,
          valueType: float,
          required: false,
          min: 0,
        }
      - label: Pricings
        name: pricings
        widget: list
        hint: 'Please specify the one price'
        minimize_collapsed: false
        collapsed: false
        summary: '{{fields.quantity}} cost(s) ${{fields.price}}'
        fields:
          - label: Quantity
            name: quantity
            widget: number
            min: 1
            default: 1
            valueType: int
          - label: Price
            name: price
            min: 0
            widget: number
            valueType: float
      - { label: ASIN, name: asin, widget: ncw-id, hidden: true }
      - {
          label: 'Merchandise',
          name: 'merchandise',
          widget: 'hidden',
          default: 'comiket',
        }
  - name: questions
    label: Questions and Answers
    create: true
    folder: content/qa
    slug: 'qa-{{order}}-{{id}}'
    fields:
      - { label: Question, name: question, widget: string }
      - { label: Answer, name: answer, widget: text }
      - {
          label: Order of qa card,
          name: order,
          default: 1,
          valueType: int,
          widget: number,
          min: 1,
        }
      - { label: ID, name: id, widget: ncw-id, hidden: true }
