backend:
  name: git-gateway

media_folder: static/images/uploads
public_folder: images/uploads
publish_mode: editorial_workflow

collections:
  - label: 'Landing Page'
    name: 'Landing Page'
    files:
      - label: Landing Page
        name: landing
        file: content/landingPage.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro text, name: intro, widget: text }
          - { label: Image, name: image, widget: image }
          - {
              label: New Release 1,
              name: release1,
              widget: relation,
              collection: weiss,
              searchFields: ['name.first', 'producttype'],
              valueField: 'name.first',
              displayFields: ['name', 'asin', 'producttype'],
            }
  - name: weiss
    label: Weiss
    create: true
    folder: content/weiss
    slug: '{{name}}'
    fields:
      - { label: Name, name: name, widget: string }
      - { label: ASIN, name: asin, widget: string }
      - {
          label: Product Type,
          name: producttype,
          widget: select,
          options:
            [
              'Trial Deck',
              'Trial Deck+',
              'Box of Trial Decks',
              'Booster Box',
              'Carton of Booster Boxes',
              'Extra Booster',
              'Other',
            ],
          default: ['Booster Box'],
        }
      - { label: Series, name: series, widget: string }
      - { label: Product Primary Color Hex, name: color, widget: string }
      - { label: Description, name: description, widget: text, required: false }
      - { label: Image, name: image, widget: image }
      - label: Pricings
        name: pricings
        widget: list
        minimize_collapsed: true
        summary: '{{fields.quantity}} cost(s) ${{fields.price}}'
        fields:
          - label: Quantity
            name: quantity
            widget: number
            min: 1
            valueType: int
          - label: Price
            name: price
            min: 0
            widget: number
            valueType: float
      - {
          label: Shipping Weight,
          name: weight,
          widget: number,
          valueType: float,
          required: false,
        }
      - {
          label: Preorder date,
          name: preorder,
          widget: datetime,
          dateFormat: 'MM.DD.YYYY',
          timeFormat: false,
        }
      - {
          label: Release date,
          name: release,
          widget: datetime,
          dateFormat: 'MM.DD.YYYY',
          timeFormat: false,
        }
